apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manifests/common/cert-manager/cert-manager/base
- manifests/common/cert-manager/kubeflow-issuer/base
- manifests/common/istio-1-9/istio-crds/base
- manifests/common/istio-1-9/istio-namespace/base
- manifests/common/istio-1-9/istio-install/base
- manifests/common/dex/overlays/istio
# - manifests/common/oidc-authservice/base
- manifests/common/knative/knative-serving/base
- manifests/common/istio-1-9/cluster-local-gateway/base
- manifests/common/kubeflow-namespace/base
- manifests/common/kubeflow-roles/base
- manifests/common/istio-1-9/kubeflow-istio-resources/base
- manifests/apps/pytorch-job/upstream/overlays/kubeflow